# -*- coding: utf-8 -*-
"""Continuando com Collections

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S-UbYURiOI7FBYmndXxYZNociLWyWWfP
"""

usuarios_data_science = [15, 23, 43, 56]
usuarios_machine_learning = [13, 23, 56, 42]

assistiram = usuarios_data_science.copy()
assistiram.extend(usuarios_machine_learning)
print(assistiram)

print(len(assistiram))

print(set(assistiram))

print(set([1, 2, 3, 1]))

print({4, 1, 2, 3, 1})

print(type({1, 2}))

usuarios_data_science = {15, 23, 43, 56}
usuarios_machine_learning = {13, 23, 56, 42}

print(usuarios_machine_learning)

try:
  print(usuarios_machine_learning[3])
except Exception as err:
  print(err)

for usuario in set(assistiram):
    print(usuario)

usuarios_data_science = {15, 23, 43, 56}
usuarios_machine_learning = {13, 23, 56, 42}

print('|', usuarios_data_science | usuarios_machine_learning)

print('&', usuarios_data_science & usuarios_machine_learning)

print('-', usuarios_data_science - usuarios_machine_learning)

fez_ds_mas_nao_fez_ml = usuarios_data_science - usuarios_machine_learning
print(fez_ds_mas_nao_fez_ml)

print(15 in fez_ds_mas_nao_fez_ml)

print(23 in fez_ds_mas_nao_fez_ml)

print(usuarios_data_science ^ usuarios_machine_learning)
